/* config.h.  Generated by configure.  */
/* Copyright 2001 Enhanced Software Technologies Inc.
 * Released under GNU General Public License V2 or Above
 * See http://www.gnu.org for more information about the terms of
 * the GNU General Public License.
 * $Date: 2007-03-26 05:39:27 +0000 (Mon, 26 Mar 2007) $
 * $Revision: 188 $
 */

#ifndef CONFIG_H
#define CONFIG_H 1

/* autoconf changes these. */
#define HAVE_STRING_H 1
#define HAVE_UNISTD_H 0
#define HAVE_STDLIB_H 1
#define HAVE_STDARG_H 1
#define HAVE_SCSI_SCSI_H 0
#define HAVE_SCSI_SCSI_IOCTL_H 0
#define HAVE_SCSI_SG_H 0
#define HAVE_SYS_GSCDDS_H 0
#define HAVE_CAMLIB_H 0
#define HAVE_SYS_SCSI_IMPL_USCSI_H 0
#define HAVE_SYS_SCSI_CTL_H 0
#define HAVE_DSLIB_H 0
#define HAVE_DU_DEFS_H 0
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_FCNTL_H 1
#define HAVE_SYS_IOCTL_H 0
#define HAVE_SYS_MTIO_H 0
#define HAVE_DDK_NTDDSCSI_H 0

#define HAVE_MEMSET 1

#define WORDS_BIGENDIAN 0

#endif

